---
- hosts: all
  vars:
    remote_user: vagrant
  remote_user: "{{ remote_user }}"
  become: true
  tasks:

# ssh keys
    - name: Copy keys with owner and permissions
      ansible.builtin.copy:
        src: ~/.ssh/{{item}}
        dest: /home/{{ remote_user }}/.ssh/{{item}}
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
        mode: preserve
      loop:
        - id_ecdsa
        - id_ecdsa.pub

# docker
    - name: install dependencies
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    - name: add GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
    - name: add docker repository to apt
      apt_repository:
        repo: deb https://download.docker.com/linux/debian bullseye stable
        state: present
    - name: install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    - name: check docker is active
      service:
        name: docker
        state: started
        enabled: yes
    - name: Ensure group "docker" exists
      ansible.builtin.group:
        name: docker
        state: present
    - name: adding remote_user to docker group
      user:
        name: "{{ remote_user }}"
        groups: docker
        append: yes
    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /usr/local/bin/docker-compose
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"

# git
    - name: Install git
      apt:
        name: git
        state: present

# node
    - name: Install the gpg key for nodejs LTS
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: Install the nodejs LTS repos
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_18.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes

    - name: Install nodejs
      apt:
        name: nodejs
        state: present

# dotnet
    - name: Create a temp directory for storing the dotnet packages
      ansible.builtin.file:
        path: /etc/dotnet_temp
        state: directory
        group: "{{ remote_user }}"
        owner: "{{ remote_user }}"

    - name: Get URL for dotnet
      get_url:
        url: "https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb"
        dest: /etc/dotnet_temp/packages-microsoft-prod.deb

    - name: Add to dpgk repository
      ansible.builtin.shell:
        cmd: dpkg -i /etc/dotnet_temp/packages-microsoft-prod.deb

    - name: Update cache
      apt:
        update_cache: yes

    - name: Install dotnet
      apt:
        name: dotnet-sdk-7.0
        state: present
        update_cache: yes

    - name: Delete dotnet_temp directory
      ansible.builtin.file:
        path: /etc/dotnet_temp
        state: absent
